import type { Metadata } from 'next'
import './globals.css'
import Theme from "@/context/Theme";


export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body>
            <Theme>{children}</Theme>
          </body>
      </html>
  )
}
